### ISSUE TITLE
Ordering the pcb's

### ISSUE THREAD

**Issue by sgoudsme** [mastrogippo/1337-3310-WiFi#2]
Hi,
I'm interested in building one of these 3310 ESP boards. 
I'm a  software engineer, familiar with esp-idf on eps32. So, programming the espressif will not be a problem.
I just want to know: I see that you describe some "problems" in the pcb, probably because it was the first prototype. But I see that (comparing the foto's and the gerber files) there is eg a ufl connector on gerber. Does this mean you have fixed the problems, but not tested them?
The thing I want the know in essence, If i order the pcb's online via eg jlcpcb, do you think there is a need of a rework or should it work as is? I don't need any guarantees, but more knowing that -as good as you've tested it- that it should work?

I don't find any contact information of you, you can always contact me at sibrecht@goudsmedt.be

Regards,
Sibrecht

**Comment by mastrogippo** [comment]
Hi Sibrecht, as far as I remember, in the latest version everything works except for the buzzer. You'll have to short C26 and make sure you don't turn on the buzzer pin with a DC signal, or you'll burn it (it's a speaker, not a piezo).
I should have some spare PCBs, I can send you some if you cover shipping costs. Feel free to write me at [my name]@[my name].it
Cheers
